### ISSUE TITLE
moprosoft

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-teccaf#1]
[MOPROSOFT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-teccaf/files/12807245/MOPROSOFT.pdf)

**Comment by Heidi-19** [comment]
Calificació: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
